### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by Ha0Tang** [TAMU-VITA/AutoGAN#11]
[Epoch 14/15] [Batch 300/782] [D loss: 1.949833] [G loss: 0.263498]
[Epoch 14/15] [Batch 400/782] [D loss: 1.945486] [G loss: -0.067332]
[Epoch 14/15] [Batch 500/782] [D loss: 1.483213] [G loss: 0.168653]
[Epoch 14/15] [Batch 600/782] [D loss: 2.166453] [G loss: 0.740634]
[Epoch 14/15] [Batch 700/782] [D loss: 1.869209] [G loss: 0.684715]
=> train controller...
arch: tensor([0, 0, 2, 0], device='cuda:1')
calculate Inception score...
get Inception score of 1.725852608680725
Traceback (most recent call last):█████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:34<00:00,  1.57it/s]
  File "search.py", line 199, in <module>
    main()
  File "search.py", line 170, in main
    train_controller(args, controller, ctrl_optimizer, gen_net, prev_hiddens, prev_archs, writer_dict)
  File "/home/ht/projects/AutoGAN/functions.py", line 213, in train_controller
    cur_batch_rewards = cur_batch_rewards.unsqueeze(-1) + args.entropy_coeff * entropies  # bs * 1
RuntimeError: expected device cuda:0 but got device cuda:1

**Comment by GongXinyuu** [comment]
Can you try to specify the visible CUDA device to one single GPU, via `export CUDA_VISIBLE_DEVICES=x` (x is the gpu_id), and see if the error continues to exist?

**Comment by Ha0Tang** [comment]
It works now. Thanks.
