### ISSUE TITLE
instance segmentation and limiting the parameters

### ISSUE THREAD

**Issue by deepseek** [TAMU-VITA/AutoGAN#17]
@GongXinyuu @yueruchen 
Thanks for the hard work,
does autogan work for instance segmentation tasks.
also, is there a way to limit the parameters/flops of the searched model

**Comment by GongXinyuu** [comment]
Hi, thanks for your interest in our work. However, autogan is not designed for segmentation task. You can refer to our group's new work [FasterSeg](https://github.com/TAMU-VITA/FasterSeg), which is a NAS framework for segmentation.
