### ISSUE TITLE
Is it only the common training code？

### ISSUE THREAD

**Issue by Magilss** [TAMU-VITA/AutoGAN#4]
The NAS part seems not given in this github？

**Comment by sebwal** [comment]
Would the author care to comment on this? I also can't seem to find anything related to the controller mentioned in the paper.

**Comment by 809253928** [comment]
hey，i need the rnn controller code

**Comment by GongXinyuu** [comment]
Hi all, sorry for the delay. The search part will be released soon in several days.

**Comment by GongXinyuu** [comment]
NAS part uploaded.
