### ISSUE TITLE
Setup new models

### ISSUE THREAD

**Issue by bjarnege** [TAMU-VITA/AutoGAN#5]
Hello together,
how can i train a new model based on images?

**Comment by RunenrCode** [comment]
I have the same question, have you resolved?

**Comment by GongXinyuu** [comment]
@bjarnege That means using a different dataset?

**Comment by GongXinyuu** [comment]
For the new dataset, you should write your own dataloader.  Make sure the new dataset can use the Inception score as the evaluation metric.
