### ISSUE TITLE
pip install is giving errors

### ISSUE THREAD

**Issue by kunwardeeps** [TAMU-VITA/AutoGAN#6]
This is in python v3.6.9 conda environment in Windows:

  ERROR: Could not find a version that satisfies the requirement torch==1.1.0 (from -r requirements.txt (line 9)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.1.0 (from -r requirements.txt (line 9))

Can you please fix the version issue?

**Comment by Borda** [comment]
You can install it separately
`pip install "torch==1.1.0"`
https://pypi.org/project/torch/#history

**Comment by kunwardeeps** [comment]
I still get the same error. If I install a different version, I am afraid it might have a conflict elsewhere.

**Comment by GongXinyuu** [comment]
Hi, I think torch >=1.1.0 would be okay for this code. You can install it following official instruction https://pytorch.org 

I'll fix the version issue in README later. Thanks.
