### ISSUE TITLE
how to generate fid_stats_cifar10_train.npz 

### ISSUE THREAD

**Issue by RunenrCode** [TAMU-VITA/AutoGAN#7]
Hello together,
 I'm training a new model with other datasets. The other datasets are ready and can be trained normally, but the inception score and FID score are not correct . because I use the downloaded fid_stats_cifar10_train.npz. 
My question: What is stored in fid_stats_cifar10_train.npz?

**Comment by GongXinyuu** [comment]
Hi, the "fid_stats_cifar10_train.npz" file stores the statistic data for CIFAR10, so you should generate another "*.npz" file for the dataset you used. You can use [utils/cal_fid_stat.py](https://github.com/TAMU-VITA/AutoGAN/blob/master/utils/cal_fid_stat.py) to generate the statistical file for your dataset.

For more details please refer to https://github.com/bioinf-jku/TTUR

And also, this file won't affect the calculation of Inception score, but only FID score.
